# Generated by Django 3.1.5 on 2021-01-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='set',
            new_name='sets',
        ),
    ]
